server:
  port: 8761
eureka:
  instance:
    hostname: localhost
#    making false so that this repo won't be as a client for the eureka server.
  client:
    register-with-eureka: false
    fetch-registry: false
