server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/users

        - id: rating-service
          uri: http://localhost:8083/
          predicates:
            - Path=/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingsCircuitBreaker
                fallbackUri: forward:/fallback/ratings

        - id: hotel-service
          uri: http://localhost:8082/
          predicates:
            - Path=/hotel/**
          filters:
            - name: CircuitBreaker
              args:
                name: hotelCircuitBreaker
                fallbackUri: forward:/fallback/hotel
