server:
  port: ${server.port}
spring:
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}
      database: ${spring.data.mongodb.database}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka