server:
  port: ${server.port}  # Port on which the service will run

spring:
  datasource:
    url: ${spring.datasource.url}  # Pulling from Config Server
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}  # Automatically update schema (for development)
    properties:
      hibernate:
        dialect: ${spring.jpa.properties.hibernate.dialect}
    show-sql: ${spring.jpa.properties.hibernate.show-sql}   # Show SQL queries in logs

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG  # Added logging for datasource configuration
    org:
      springframework:
        cloud: INFO
        boot: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
