# Set the port for Config Server to run on
#server.port=8888
#
## Set the application name for the Config Server
#spring.application.name=config-server
#
## Git URI where configuration files are stored
#spring.cloud.config.server.git.uri=https://github.com/LokiNaik/config-repo.git
#
## Optional: Specific directory in the Git repo to search for configuration files
#spring.cloud.config.server.git.searchPaths=application
#
## Optional: Branch name in Git to use (if different from "master")
#spring.cloud.config.server.git.default-label=main
#
## Enable Git-based config server support
#spring.cloud.config.server.git.cloneOnStart=true
#
## Optional: Enable health and info endpoints for monitoring
#management.endpoints.web.exposure.include=health,info

server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LokiNaik/config-repo.git  # Correct repository URL
          searchPaths: application  # Make sure this folder exists
          cloneOnStart: true
          force-pull: true
          default-label: main  # Ensure this label exists in the repo
management:
  endpoints:
    web:
      exposure:
        include: health,info

