server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LokiNaik/config-repo.git
          searchPaths: application
          cloneOnStart: true
          force-pull: true
          default-label: main  # Ensure this label exists in the repo
management:
  endpoints:
    web:
      exposure:
        include: health,info